### ISSUE TITLE
Make item forms (new/edit) similar

### ISSUE THREAD

**Issue by differentreality** [differentreality/supplies_tracker#24]
- [ ]  description is huge in edit
- [x]  Labels are different, which can be confusing Fixed in commit **'do/undo false migrations , edit and create item same labels **'**** ( #33 ) 
- [x]  order of prices (bought and reimbursement) is not the same in both forms Fixed in #30 
- [x]  image is required in edit (and shouldn't. Separate issue for this #23) Fixed in #30
